name: raytracer
version: 0.2.0
author: Demis Bellot <demis.bellot@gmail.com>
description: TypeScript's Ray Tracer ported to Dart
homepage: https://github.com/filiph/raytracer
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^1.0.1
transformers:
  - dart_to_js_script_rewriter
  - $dart2js:
      checked: false
      minify: false
      #commandLineOptions: ['--trust-type-annotations', '--trust-primitives']
