name: raytracer
version: 0.4.0-nullsafety.0
authors:
  - Demis Bellot <demis.bellot@gmail.com>
  - Filip Hracek <filip.hracek@gmail.com>
description: TypeScript's Ray Tracer ported to Dart
homepage: https://github.com/filiph/raytracer

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.4
  build_web_compilers: ^2.13.0
