name: raytracer
version: 0.3.0
authors:
  - Demis Bellot <demis.bellot@gmail.com>
  - Filip Hracek <filip.hracek@gmail.com>
description: TypeScript's Ray Tracer ported to Dart
homepage: https://github.com/filiph/raytracer

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
